name: Node Runner Bot

on:
  push:
    branches:
      - Tech_VJ
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pytest and Runner Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          npm install -g pm2

      - name: Boot Application
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          OTHER_DB_URI: ${{ secrets.DATABASE_URI }}
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pm2 start bot.py --name "vj-filter-bot" --interpreter ./venv/bin/python3
          sleep 10
          pm2 logs --no-daemon
